export const projects = [
  {
    slug: 'supero',
    name: 'Supero Digital Ecosystem',
    client: 'Supero PH',
    type: 'E-commerce + Lead Recovery',
    year: '2026',
    tags: ['Next.js 14', 'Supabase', 'Claude AI', 'React'],
    summary: 'A Metro Manila pet food brand was losing 20 inquiries per day to Messenger. We built a structured platform that captures every lead, handles inquiries with AI, and shows the owner exactly how much revenue was recovered.',
    problem: 'The brand had no website — only a Facebook Page. Every inquiry came in as a Messenger DM. When the owner was busy, messages sat unanswered. No emails captured, no re-engagement possible, no way to track how many potential customers were lost. Over 90 days, an estimated ₱180,000+ in potential orders evaporated.',
    solution: 'Phase 1 of a 4-phase ecosystem: a product storefront with variant pricing, social auth (Google/Facebook login) that captures email on every checkout attempt, an AI-powered chatbot (Claude API) that handles the 20 daily inquiries in Taglish automatically, and an owner dashboard showing lead recovery rate, revenue, and weekly trends.',
    results: [
      { metric: '78%', label: 'Lead capture rate', sub: 'Was 0% with Messenger-only workflow' },
      { metric: '₱148k', label: 'Pipeline recovered', sub: 'In 90 days post-launch' },
      { metric: '20+', label: 'Daily inquiries handled', sub: 'By AI, not manually' },
      { metric: '0', label: 'Manual replies needed', sub: 'For standard product questions' },
    ],
    stack: ['Next.js 14 App Router', 'Supabase (PostgreSQL + Auth)', 'Claude claude-sonnet-4-20250514 API', 'Vercel', 'Facebook/Google OAuth'],
    phases: [
      { phase: 'Phase 1 (Live)', desc: 'Retail storefront, lead capture, AI chatbot, owner dashboard' },
      { phase: 'Phase 2 (Scoped)', desc: 'Wholesale hub router — distributor dashboards, geo-radius routing' },
      { phase: 'Phase 3 (Scoped)', desc: 'Find-a-Puppy marketplace — breeder listings, breed trend analytics' },
      { phase: 'Phase 4 (Scoped)', desc: 'Farm & event booking — calendar, subscriptions, automated ticketing' },
    ],
  },
  {
    slug: 'tgb',
    name: 'TGB Jewelry Automation Engine',
    client: 'The Gold Bar Jewelry',
    type: 'Content & Distribution Automation',
    year: '2025',
    tags: ['Google Apps Script', 'Facebook Graph API', 'Google Sheets', 'n8n'],
    summary: 'A layaway jewelry brand active since 2016 was spending 8+ hours per month on manual Facebook posting across 40 groups. We automated the entire pipeline — content generation, scheduling, distribution, and logging.',
    problem: 'TGB built a distribution network of 40 Facebook groups over years. Posting manually to all 40 groups on a Mon/Wed/Fri/Sun cadence required 3–5 minutes per post, per group. That\'s 160 posts per month — over 13 hours of repetitive work. The brand voice was inconsistent, posting was occasionally missed, and there was no way to track which groups were responding.',
    solution: 'A Google Apps Script engine that reads from a content calendar in Google Sheets, generates aspirational Taglish captions using a locked brand voice template (layaway hook: "10% monthly, pwede na!"), and distributes to all 40 groups via the Facebook Graph API. A 3-day cooldown per group prevents spam flags. Every post logs its ID, timestamp, and status back to the Sheet.',
    results: [
      { metric: '160', label: 'Posts/month automated', sub: 'Previously 100% manual' },
      { metric: '0', label: 'Missed posting days', sub: 'Since launch' },
      { metric: '40', label: 'Groups managed', sub: 'With per-group cooldown tracking' },
      { metric: '13h', label: 'Monthly hours recovered', sub: 'Redirected to customer service' },
    ],
    stack: ['Google Apps Script', 'Facebook Graph API v18', 'Google Sheets (content calendar + log)', 'Script Properties (token storage)', 'Time-based triggers'],
    phases: [],
  },
  {
    slug: 'mhc',
    name: 'MHC Wholesale Delivery Pipeline',
    client: 'MHC Wholesale',
    type: 'Multi-Brand Automation',
    year: '2025',
    tags: ['n8n', 'Google Sheets', 'Facebook Graph API', 'Webhooks'],
    summary: 'A fresh food and rice wholesale delivery brand needed brand-isolated automation pipelines that could handle order notifications, content distribution, and KPI logging — all without cross-contaminating the 6 other brands in the TYG Services ecosystem.',
    problem: 'Running multiple brands from one Supabase and one n8n instance creates a risk: a misconfigured workflow can post under the wrong brand\'s name or token. MHC needed its own isolated pipeline with its own Facebook token, its own Sheets log, and its own error handling — while still fitting into the broader SVC Distribution Engine.',
    solution: 'Brand-isolated n8n workflows with per-brand token management. Each workflow has its own error handler node that logs failures and sends alerts before stopping. Order notifications trigger a webhook that formats a Taglish motherly-voice caption (savings + delivery hook) and posts to the brand\'s Facebook Page. All activity logs to a master Sheet for the SVC KPI dashboard.',
    results: [
      { metric: '100%', label: 'Brand isolation', sub: 'Zero cross-brand token leaks' },
      { metric: '0%', label: 'Error rate', sub: 'Since error handler deployment' },
      { metric: '6', label: 'Brands on same instance', sub: 'All isolated, none interfering' },
      { metric: '1', label: 'Master KPI sheet', sub: 'All brands log to one dashboard' },
    ],
    stack: ['n8n (self-hosted)', 'Facebook Graph API', 'Google Sheets API', 'Webhook triggers', 'Script Properties for token isolation'],
    phases: [],
  },
  {
    slug: 'soleblessing',
    name: 'SoleBlessing E-commerce',
    client: 'SoleBlessing Sneakers',
    type: 'Sneaker E-commerce',
    year: '2025',
    tags: ['Next.js', 'Facebook Catalog', 'COD Integration', 'n8n'],
    summary: 'A COD-first sneaker e-commerce store for the Philippine market, built with drop mechanics, Facebook catalog auto-sync, and hype-forward content automation.',
    problem: 'Philippine sneaker buyers expect COD. Existing platforms either don\'t support it well or take large commissions. The brand needed its own storefront with drop mechanics (inventory locks at announcement, releases at a set time), Facebook catalog sync for dynamic ads, and consistent "LEGIT. FRESH. YOURS." brand voice across all content touchpoints.',
    solution: 'A custom Next.js storefront with drop mechanics — products show as "Coming Soon" until release time, then unlock for purchase. Facebook catalog is synced automatically via n8n webhook on every inventory update. Content automation generates hype-forward Taglish captions on drop days and posts to Facebook/Instagram on schedule.',
    results: [
      { metric: 'COD', label: 'First checkout flow', sub: 'Primary PH payment preference' },
      { metric: 'Auto', label: 'Facebook catalog sync', sub: 'Updates on every inventory change' },
      { metric: '100%', label: 'Drop cadence hit', sub: 'No missed release announcements' },
      { metric: '0', label: 'Manual posts on drop day', sub: 'Fully automated hype pipeline' },
    ],
    stack: ['Next.js 14', 'Supabase', 'n8n (catalog sync)', 'Facebook Graph API', 'COD payment flow'],
    phases: [],
  },
  {
    slug: 'yani',
    name: 'YANI Garden Café System',
    client: 'YANI Garden Café, Amadeo',
    type: 'F&B Operations + Content',
    year: '2025',
    tags: ['Google Apps Script', 'Google Sheets', 'n8n', 'Facebook API'],
    summary: 'Operations and content automation for a garden café in Amadeo, Cavite — Tagalog-forward social content, table reservation management, and a Sunday community post workflow.',
    problem: 'A cozy garden café was posting manually to Facebook with inconsistent frequency and inconsistent tone. Reservations were managed via DM with no structured tracking. The brand voice — warm, Tagalog-forward, food + ambiance focused — wasn\'t being executed consistently because the owner was managing the café floor and social media simultaneously.',
    solution: 'GAS-powered content automation with a Tagalog voice template locked to the YANI brand (food photos + ambiance hooks, no English-heavy corporate tone). Table reservations flow into a Google Sheet via a simple form, visible to floor staff in real time. A Sunday community post workflow runs automatically, featuring a weekly special or a community story.',
    results: [
      { metric: '4x', label: 'Posting consistency', sub: 'Mon/Wed/Fri/Sun without fail' },
      { metric: '100%', label: 'Tagalog voice maintained', sub: 'No off-brand English posts' },
      { metric: '0', label: 'Lost reservations', sub: 'All tracked in Sheets' },
      { metric: '1h', label: 'Weekly time saved', sub: 'On content and reservation admin' },
    ],
    stack: ['Google Apps Script', 'Google Sheets (reservations)', 'Facebook Graph API', 'GAS time triggers'],
    phases: [],
  },
];

export function getProjectBySlug(slug) {
  return projects.find(p => p.slug === slug) || null;
}
